MERCHANT_AI_CHANNEL = "🤖｜merchant-ai"
SUPPORT_CENTER_CHANNEL = "🛟｜support-center"
RESERVE_CHANNEL = "📌｜reserve-a-beat"
SUBMIT_SALE_CHANNEL = "🧾｜submit-a-sale"
STAFF_ROLE_NAMES = ["TECHNICAL ADMIN", "THE STANDARD"]
ADMIN_COMMAND_ROLES = ["TECHNICAL ADMIN", "THE STANDARD"]
PARTNER_CATALOG_LIVE_ROLE = "Partner Catalog Live Access"
